name: Deploy to WP Engine

on:
  push:
    branches:
      - main
      - staging
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Build assets
        run: npm run build

      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSH_KEY_PRIVATE: ${{ secrets.WPE_SSH_KEY_PRIVATE }}
          WPE_SSH_KEY_PUBLIC: ${{ secrets.WPE_SSH_KEY_PUBLIC }}
          WPE_SSH_HOST: ${{ secrets.WPE_SSH_HOST }}
          REMOTE_PATH: ${{ github.ref == 'refs/heads/main' && secrets.WPE_PROD_PATH || github.ref == 'refs/heads/staging' && secrets.WPE_STAGING_PATH || secrets.WPE_DEV_PATH }}
          LOCAL_PATH: ./
          FLAGS: -azvr --delete --exclude-from=.gitignore 